#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# -- General configuration ------------------------------------------------

# Derive the subscriber tags to use for this build from the
# corresponding version information.
# The short X.Y version.

# -- Include Sphinx extensions ------------------------------------------------
extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.ifconfig',
    'sphinx_design',
    'sphinx_copybutton',
    'sphinx_reredirects',
    'sphinx.ext.graphviz',
    'sphinx_new_tab_link',
    'myst_parser',
]

#-- MyST config ----------------------------------------------------------------

myst_heading_anchors = 6

#-- copy button config ---------------------------------------------------------

copybutton_exclude = '.linenos, .gp, .go'

#-- Linkcheck config -----------------------------------------------------------

sphinx_tabs_valid_builders = ['linkcheck']
linkcheck_retries = 3
#linkcheck_anchors_ignore = ['L189-L192']
linkcheck_allow_unauthorized = True
# Links that shouldn't get checked for validity
linkcheck_ignore = [
    r'http://localhost:\d+/?',
    'http://.*[.]local',
    r'https://source.foundries.io/*',
    r'https://github.com/foundriesio/*', # rate limits, other issues
]
# Time in seconds to wait for a response. May result in false errors, but also keeps things from timing out
linkcheck_timeout = 10

# Add any paths that contain templates here, relative to this directory.
#templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.md'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'FoundriesFactory Partners'
copyright = '2017-%Y, Foundries.io, Ltd'
author = 'Foundries.io, Ltd.'


# The language for content autogenerated by Sphinx. Refer to documentation
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
#exclude_patterns = []

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# Standard epilog to be included in all files.
#rst_epilog = '''
version_match="0.1"
# -- HTML output config -------------------------------------------------------

# The theme to use for HTML pages
html_theme = 'pydata_sphinx_theme'

# version switcher config
json_url = 'https://docs.foundries.io/latest/_static/switcher.json'

# Pydata Theme options
html_theme_options = {
    'pygments_light_style': 'default',
    'collapse_navigation': 'False',
    'show_version_warning_banner': True,
    'logo': {
        'alt_text': 'FoundriesFactory partner logo',
        'image_light': '_static/logo.png',
        },
#    'logo_link': '',
    'collapse_navigation': True,
    'show_nav_level': 2,
    'navbar_start': ['navbar-logo', 'version-switcher'],
    'navbar_center': ['navbar-nav'],
    #'navbar_persistent': [],
    'navbar_end': ['navbar-icon-links'],
    'secondary_sidebar_items': ['page-toc'],
    #'article_footer_items': [],
    #'content_footer_items': [],
    'footer_start':['copyright'],
    #'footer_center': ['footer'],
    #'footer_end': [],
    'switcher': {
        'json_url': json_url,
        'version_match': version_match,
        },
    'check_switcher': False,
    "header_links_before_dropdown": 4,
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/foundriesio/meta-partner/tree/qualcomm",
            "icon": "fa-brands fa-github",
            },
        ],
    "article_header_start": ["breadcrumbs"],
}
html_context = {
   "default_mode": "light"
}

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add custom CSS files.
#html_css_files = [
#    'css/custom.css'
#]

#html_js_files = []

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {
#        '**': ['sidebar-nav-bs'],
        # Removes left sidebar from homepage
#        'index': [],
#        'glossary/index':[],
#        }
# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# Enable numref
numfig = True
